SELECT
        raw_rechnzeile.Nr AS rechnzeile_id,
        raw_rechnzeile.PAT_Name AS patient_name,
        raw_rechnzeile.PAT_Geburtsjahr AS patient_year_of_birth,
        YEAR(DATE '1801-01-01' + to_days(raw_rechnzeile.REZ_Datum::INT)) - raw_rechnzeile.PAT_Geburtsjahr AS patient_age,
        NULLIF(raw_rechnzeile.PAT_Status, '') AS patient_status,
        raw_rechnzeile.REZ_Nr AS rezept_id,
        DATE '1801-01-01' + to_days(raw_rechnzeile.Von::INT) AS rezept_von,
        DATE '1801-01-01' + to_days(raw_rechnzeile.Bis::INT) AS rezept_bis,
        raw_rechnzeile.Faktor::NUMERIC(10, 4) AS Faktor,
        raw_rechnzeile.Anzahl AS number_of_line_items,
        raw_rechnzeile.Brutto::NUMERIC(10, 4) AS total_gross,
        raw_rechnzeile.Zuzahlung::NUMERIC(10, 4) AS supplement,
        raw_rechnzeile.Netto::NUMERIC(10, 4) AS total_net,
        raw_rechnzeile.Eigenanteil::NUMERIC(10, 4) AS own_share,
        raw_rechnzeile.Text,
        raw_rechnzeile.REC_Nummer AS invoice_number,
        NULLIF(raw_rechnzeile.Abrechnungscode, '') AS billing_code,
        DATE '1801-01-01' + to_days(raw_rechnzeile.REZ_Datum::INT) AS invoice_date,
        NULLIF(raw_rechnzeile.KAS_IK, '') AS ik_number,
        NULLIF(raw_rechnzeile.KAS_Name, '') AS insurance_name,
        raw_rechnzeile.TAR_Name AS tariff_name,
        NULLIF(raw_rechnzeile.DIA_Diagnose, '') AS diagnosis,
        raw_rechnzeile.Arbeitsunfall::BOOLEAN AS work_accident,
FROM
        {{ source('starke_praxis', 'raw_rechnzeile') }}
