version: 2

models:
  - name: stg_employees
    config:
      meta:
        dagster:
          group: staging

  - name: stg_appointments
    config:
      meta:
        dagster:
          group: staging

  - name: stg_receipts
    config:
      meta:
        dagster:
          group: staging

  - name: stg_invoices
    config:
      meta:
        dagster:
          group: staging

  - name: stg_invoice_line_items
    config:
      meta:
        dagster:
          group: staging
