version: 2

models:
  - name: stg_employees
    columns:
      - name: employee_id
        data_tests:
          - unique
          - not_null
    config:
      meta:
        dagster:
          group: staging

  - name: stg_appointments
    columns:
      - name: appointment_id
        data_tests:
          - unique
          - not_null
    config:
      meta:
        dagster:
          group: staging

  - name: stg_receipts
    columns:
      - name: receipt_id
        data_tests:
          - unique
          - not_null
    config:
      meta:
        dagster:
          group: staging

  - name: stg_invoices
    columns:
      - name: invoice_id
        data_tests:
          - unique
          - not_null
      - name: receipt_id
        data_tests:
          - unique:
              config:
                severity: warn
                error_if: ">1000"
                warn_if: ">0"
    config:
      meta:
        dagster:
          group: staging

  - name: stg_invoice_line_items
    columns:
      - name: invoice_line_item_id
        data_tests:
          - unique
          - not_null
    config:
      meta:
        dagster:
          group: staging
